# Generated by Django 5.0.4 on 2024-04-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
